### ISSUE TITLE
s() doesn't work sensibly

### ISSUE THREAD

**Issue by jarich** [scrottie/autobox-Core#12]
sub s          { $_[0] =~ s{$_[1]}{$_[2]} }

Documentation says:

    Works the same as C<< s/// >>.

Which it does.  s/// returns the number of substitutions performed in both list and scalar contexts.  So that's what this returns. 
You can't do:

    "the cat sat on the mat"->s(qr/cat/, "dog")->say;

or

    $foo->s(qr/cat/, "dog")->say;

which seems more autoboxish. Perhaps this shouldn't work on literals, but it should probably return $_[0] when that's a scalar.

**Comment by scrottie** [comment]
Oof.  So, I didn't have a g on the s/$_[1]/$_[2]/.  There's no count to return, only success/failure.

Which creates a SNOBOL like idiom if you want to do global replace:

    again:
        $str->s("foo", "bar") and goto again;

This is terrible.  But kind of funny.

Since I couldn't muster the gumption to remove the ops, I decided to go with Want to make this maybe somewhat more useful.  If it generates smoke, I'll pull it out (unless someone beats me to doing that).

$string->s("foo", "bar") returning a string in non-boolean context is potentially backward compat.  Many strings will pass as true booleans, so this will superficially appear okay, but successful substitutions resulting in '', '0', etc will appear to have failed if the result is tested by some other means than directly by something Want considers to have boolean context.

As Schwern rightly pointed out, it's a doc headache.  I'm leaving the bulk of the headachy docs here (about how this can go wrong), not in the POD.  (If you wound up here due to this problem, you have my apologies; feedback welcome.)
