### ISSUE TITLE
We have a subroutine called "backtick" but we get "rpt" instead of repeat?

### ISSUE THREAD

**Issue by jarich** [scrottie/autobox-Core#15]
There is no consistency between function names.  I'd prefer "repeat" over "rpt", personally.

**Comment by scrottie** [comment]
Since I never really managed to remove operators, I should actually implement these suggestions.

"backtick should probably be called qx() #16" was fixed in that ticket.  jarich added repeat() in 69ef63, and the docs document repeat(), not rpt() (I can haz Unixy names?).  It looks like x is also in there as an alias for repeat and is doc'd.  So I'm marking this closed unless anyone sees anywhere this was missed.  Thanks everyone!
