### ISSUE TITLE
I think that it should remove the '~~' in the code.

### ISSUE THREAD

**Issue by gwankyun** [scrottie/autobox-Core#25]
The smartmatch has been signed experimental.

**Comment by xenu** [comment]
Indeed, smartmatch since 5.18 is marked as experimental and I'm not really sure how we should go about it. We don't know how it will behave (or whether it will still exist) in future versions of perl. Currently `~~` is used in `->grep` and `->first`.

Aside from smartmatch deprecation, these two have another problem. Both of them are using nifty symbol-table-change-in-eval trick to hide it from perls < 5.10 without noticeable performance hit. While it doesn't cost us performance, I hate idea of maintaining two **incompatible** versions of a method, especially when `eval` comes into play. I don't really think that supporting perl 5.8 in 2015 that important.

Here are possible solutions:

1. Keep it as is
2. Keep only smartmatch version
3. Keep <5.10 version
4. Something else? Maybe make it only accept coderefs?

Fist solution is IMHO unacceptable.

Second solution makes sense only if we will define `->grep` in docs as a method that smartmatches argument against `$_` in grep, that protects us from any future smartmatch behaviour changes. However, if smartmatch will get removed (I think it's unlikely), we'll have to redefine `->grep` behaviour again. The funny thing is, currently, `->grep` has no documented behaviour.

Third one is my favourite, it will guarantee consistent behaviour no matter how smartmatch will be changed in future versions of perl (and will help to sustain perl 5.8 support, or should I say, extend its agony).

Regarding `->first`, I don't quite understand why it is using smartmatch at all (it is only used to match a regex, WHY?), and I'm pretty sure that 3. is obvious solution for it.

What you think @scrottie and others?

**Comment by scrottie** [comment]
This code came from perl5i, so the theme of "unified, modern Perl behavior on all versions of Perl" is strong in it.  Indeed, perl5i uses autobox::Core, and the perl 5.8 support patches came from there.  But that project is less active than it used to be and perl 5.8 is older than it was.

I agree that this:

                return List::Util::first( sub { $_ =~ m/$filter/ }, @$array );

Is, for many reasons, preferable to this:

         eval '
            ...
                     return List::Util::first( sub { $_ ~~ $filter }, @$array );
            ...
        ' or croak $@;

``~~`` is problematic for older perls and now newer perls.  Trying to keep that around doesn't help us at all.

I agree that option #3 is the most reasonable.  I also don't know why it is using smart match other than that maybe there was a mind toward eventually migrating the code to that because it's newer and possibly faster.

If the latest version of autobox still supports 5.8, I wouldn't mind keeping 5.8 there if there's no effort for doing so.

Thanks for working that.  (Any other opinions?)

**Comment by xenu** [comment]
Since no one opposed, I've removed these evals. Unfortunately, few tests in grep.t were expecting smartmatch, so I've removed them. Additionally I've unified arguments of first() and grep(), for sake of consistency.

**Comment by scrottie** [comment]
At a glance, that all looks reasonable.
